"""
Direct PDF-as-input ingestion pipeline: reads a *generated knowledge PDF*
(the exact format pdf_generator.py produces — "ID — Question" / answer /
"intent: ..." blocks grouped under category headings), extracts the Q&A
pairs, and embeds+indexes them with the same rag_store used by the chat
engine.

This exists as an alternative entry point to /api/gym/{id}/config for cases
where you already have an approved PDF (generated by the wizard, or hand-
edited afterwards) and want to (re)index straight from that file instead of
resubmitting the wizard form.
"""
import re
import io
from pypdf import PdfReader

from .pdf_generator import QA_SCHEMA

CATEGORY_NAMES = {q["category"] for q in QA_SCHEMA}
QID_RE = re.compile(r"^([A-Z]+_\d+)\s*[—\-]\s*(.+)$")
INTENT_RE = re.compile(r"^intent:\s*(.+)$", re.IGNORECASE)
UNSET_RE = re.compile(r"\[[a-zA-Z0-9_]+\s+not set\]")
FALLBACK_TEXT = "i don't have confirmed information about this yet"


def extract_text(pdf_bytes: bytes) -> str:
    reader = PdfReader(io.BytesIO(pdf_bytes))
    return "\n".join(page.extract_text() or "" for page in reader.pages)


def parse_knowledge_pdf(pdf_bytes: bytes) -> list[dict]:
    """
    Returns a list of {id, category, question, answer, intent, configured}
    dicts — same shape as pdf_generator.resolve_answers()'s output, so it
    can be fed straight into build_rag_chunks()-equivalent logic.
    """
    text = extract_text(pdf_bytes)
    lines = [l.strip() for l in text.split("\n")]

    entries = []
    current_category = None
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line:
            i += 1
            continue
        if line in CATEGORY_NAMES:
            current_category = line
            i += 1
            continue
        m = QID_RE.match(line)
        if m:
            qid, question = m.group(1), m.group(2)
            i += 1
            answer_parts = []
            while i < len(lines) and not INTENT_RE.match(lines[i]):
                if lines[i]:
                    answer_parts.append(lines[i])
                i += 1
            answer = " ".join(answer_parts).strip()
            intent = ""
            not_configured_flag = False
            if i < len(lines):
                im = INTENT_RE.match(lines[i])
                if im:
                    intent_raw = im.group(1)
                    not_configured_flag = "(not configured" in intent_raw.lower()
                    intent = intent_raw.split(" (")[0].strip()
                    i += 1
            has_unset_field = bool(UNSET_RE.search(answer))
            is_fallback = FALLBACK_TEXT in answer.lower()
            entries.append({
                "id": qid,
                "category": current_category or "General",
                "question": question,
                "answer": answer,
                "intent": intent,
                "configured": not (not_configured_flag or is_fallback or has_unset_field),
                "has_unset_field": has_unset_field,
            })
            continue
        i += 1
    return entries


def extract_identity(text: str) -> dict:
    """
    Parses the header block pdf_generator.build_pdf() writes at the top of
    every knowledge PDF:
        "{Gym Name} — AI Assistant Knowledge Base"
        "Generated ... · gym_id: ... · Source: ..."
        "Phone" / "9876543210"
        "WhatsApp" / "9876543210"
        "Email" / "..."
        "Website" / "—"
        "City" / "..."
        "Maps" / "https://..."
    Used so a gym onboarded purely via PDF upload (no wizard config.json)
    still gets a name/contact info on the chat page instead of a bare
    "Gym Assistant" placeholder.
    """
    lines = [l.strip() for l in text.split("\n") if l.strip()]
    identity = {
        "gym_name": "", "primary_phone": "", "whatsapp_number": "",
        "email": "", "website": "", "city": "", "google_maps_url": "",
    }
    if lines:
        title_m = re.match(r"^(.+?)\s*[—\-]\s*AI Assistant Knowledge Base", lines[0])
        if title_m:
            identity["gym_name"] = title_m.group(1).strip()

    label_map = {
        "phone": "primary_phone", "whatsapp": "whatsapp_number",
        "email": "email", "website": "website", "city": "city", "maps": "google_maps_url",
    }
    for i, line in enumerate(lines):
        key = label_map.get(line.lower())
        if key and i + 1 < len(lines):
            value = lines[i + 1]
            if value and value != "—":
                identity[key] = value
    return identity


def build_chunks_from_pdf(gym_id: str, entries: list[dict]) -> list[dict]:
    """Same chunk shape rag_store.upsert() expects. Skips unconfigured /
    fallback / partially-filled-in answers so the bot never states a
    literal "[field not set]" placeholder to a user."""
    chunks = []
    for e in entries:
        if not e["configured"]:
            continue
        text = f"Category: {e['category']}\nQ: {e['question']}\nA: {e['answer']}"
        chunks.append({
            "id": f"{gym_id}::{e['id']}",
            "text": text,
            "metadata": {
                "gym_id": gym_id,
                "question_id": e["id"],
                "category": e["id"].split("_")[0],
                "intent": e["intent"],
                "question": e["question"],
                "answer": e["answer"],
            },
        })
    return chunks
